name: Release Charts
on:
  push:
    branches:
      - main
      - fix-chart-releaser
    paths:
      - 'charts/**'

jobs:
  release-charts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history is needed for proper diffing
      
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Install Helm
        uses: azure/setup-helm@v3
      
      - name: Add Helm repos
        run: |
          # Add commonly used Helm repositories
          helm repo add stable https://charts.helm.sh/stable
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
      
      - name: Install chart-releaser
        run: |
          mkdir -p .cr-release-packages
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.6.0/chart-releaser_1.6.0_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz
          chmod +x cr
          sudo mv cr /usr/local/bin/cr
      
      - name: Debug file changes
        run: |
          echo "Changed files:"
          git diff --name-only HEAD~1 HEAD
      
# Manual detection of chart changes
      - name: Detect chart changes
        id: manual-filter
        run: |
          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} || git diff --name-only $(git rev-parse HEAD~1) $(git rev-parse HEAD))
          echo "Changed files: $CHANGED_FILES"
          
          # Initialize outputs
          echo "guard=false" >> $GITHUB_OUTPUT
          echo "watch=false" >> $GITHUB_OUTPUT
          echo "path=false" >> $GITHUB_OUTPUT
          
          # Check if each chart directory has changes
          echo "$CHANGED_FILES" | grep -q "charts/guard/" && echo "guard=true" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" | grep -q "charts/watch/" && echo "watch=true" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" | grep -q "charts/path/" && echo "path=true" >> $GITHUB_OUTPUT
          
          # Output results for logging
          echo "Guard chart changed: $(echo "$CHANGED_FILES" | grep -q "charts/guard/" && echo "true" || echo "false")"
          echo "Watch chart changed: $(echo "$CHANGED_FILES" | grep -q "charts/watch/" && echo "true" || echo "false")"
          echo "Path chart changed: $(echo "$CHANGED_FILES" | grep -q "charts/path/" && echo "true" || echo "false")"
      
      # Debug chart changes
      - name: Debug chart changes
        run: |
          echo "Guard changed: ${{ steps.manual-filter.outputs.guard }}"
          echo "Watch changed: ${{ steps.manual-filter.outputs.watch }}"
          echo "Path changed: ${{ steps.manual-filter.outputs.path }}"
      
      # Download existing index file if it exists
      - name: Prepare index
        run: |
          # Try to download existing index.yaml if it exists
          mkdir -p .cr-index
          curl -sSfL -o .cr-index/index.yaml https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/index.yaml || true
          # If download failed, create a new empty index
          if [ ! -f .cr-index/index.yaml ]; then
            echo "Creating new index.yaml"
            echo "apiVersion: v1" > .cr-index/index.yaml
            echo "entries: {}" >> .cr-index/index.yaml
            echo "generated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> .cr-index/index.yaml
          fi
      
      # Prepare local chart dependencies
      - name: Setup local charts directory
        run: |
          # Create temporary directory for local charts
          mkdir -p .cr-local-charts
      
      # Process guard chart first (assuming it's a base chart)
      - name: Process guard chart
        if: steps.manual-filter.outputs.guard == 'true'
        run: |
          echo "Processing guard chart..."
          
          # Create release directory
          mkdir -p .cr-release-packages
          
          # Build dependencies and package
          helm dependency build charts/guard
          helm package charts/guard -d .cr-release-packages
          
          # Copy to local charts directory for dependency resolution
          cp .cr-release-packages/guard-*.tgz .cr-local-charts/ || true
      
      # Process watch chart second (may depend on guard)
      - name: Process watch chart
        if: steps.manual-filter.outputs.watch == 'true'
        run: |
          echo "Processing watch chart..."
          
          # If there are local dependencies, try to resolve them
          if grep -q "name: guard" charts/watch/Chart.yaml; then
            echo "Local dependency detected, adding local chart"
            GUARD_TGZ=$(ls -1 .cr-local-charts/guard-*.tgz 2>/dev/null || echo "")
            if [ -n "$GUARD_TGZ" ]; then
              mkdir -p charts/watch/charts
              cp $GUARD_TGZ charts/watch/charts/
            fi
          fi
          
          # Build dependencies and package
          helm dependency build charts/watch
          helm package charts/watch -d .cr-release-packages
          
          # Copy to local charts directory for dependency resolution
          cp .cr-release-packages/watch-*.tgz .cr-local-charts/ || true
      
      # Process path chart last (may depend on guard or watch)
      - name: Process path chart
        if: steps.manual-filter.outputs.path == 'true'
        run: |
          echo "Processing path chart..."
          
          # If there are local dependencies, try to resolve them
          if grep -q "name: guard\|name: watch" charts/path/Chart.yaml; then
            echo "Local dependency detected, adding local charts"
            DEPENDENCY_TGZS=$(ls -1 .cr-local-charts/*.tgz 2>/dev/null || echo "")
            if [ -n "$DEPENDENCY_TGZS" ]; then
              mkdir -p charts/path/charts
              cp .cr-local-charts/*.tgz charts/path/charts/
            fi
          fi
          
          # Build dependencies and package
          helm dependency build charts/path
          helm package charts/path -d .cr-release-packages
      
      # Upload all packaged charts at once
      - name: Upload charts
        if: steps.manual-filter.outputs.guard == 'true' || steps.manual-filter.outputs.watch == 'true' || steps.manual-filter.outputs.path == 'true'
        run: |
          if [ -n "$(ls -A .cr-release-packages)" ]; then
            echo "Uploading packaged charts..."
            cr upload -o "${{ github.repository_owner }}" -r "${{ github.event.repository.name }}" -p .cr-release-packages --token "${{ secrets.GITHUB_TOKEN }}" --skip-existing
          else
            echo "No charts to upload"
          fi
      
      # Update and push index
      - name: Update and push index
        if: steps.manual-filter.outputs.guard == 'true' || steps.manual-filter.outputs.watch == 'true' || steps.manual-filter.outputs.path == 'true'
        run: |
          cr index -o "${{ github.repository_owner }}" -r "${{ github.event.repository.name }}" -p .cr-release-packages -c https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/ -i .cr-index/index.yaml
          
          # Setup pages branch if it doesn't exist
          git fetch origin gh-pages || git branch gh-pages
          
          # Checkout gh-pages branch
          git checkout gh-pages || (git checkout --orphan gh-pages && git rm -rf . && git clean -fxd)
          
          # Copy the updated index to the root and commit
          cp .cr-index/index.yaml .
          
          # Add, commit and push if there are changes
          git add index.yaml
          git diff --staged --quiet || (git commit -m "Update Helm chart index" && git push origin gh-pages)
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
