name: Release Charts
on:
  push:
    branches:
      - main
      - fix-chart-releaser
    paths:
      - 'charts/**'

jobs:
  release-charts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history is needed for proper diffing
      
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Install Helm
        uses: azure/setup-helm@v3
      
      - name: Add Helm repos
        run: |
          # Add commonly used Helm repositories
          helm repo add stable https://charts.helm.sh/stable
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
      
      - name: Install chart-releaser
        run: |
          mkdir -p .cr-release-packages
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.6.0/chart-releaser_1.6.0_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz
          chmod +x cr
          sudo mv cr /usr/local/bin/cr
      
      - name: Debug file changes
        run: |
          echo "Changed files:"
          git diff --name-only HEAD~1 HEAD
      
      # Manual detection of chart changes
      - name: Detect chart changes
        id: manual-filter
        run: |
          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} || git diff --name-only $(git rev-parse HEAD~1) $(git rev-parse HEAD))
          echo "Changed files: $CHANGED_FILES"
          
          # Initialize outputs
          echo "guard=false" >> $GITHUB_OUTPUT
          echo "watch=false" >> $GITHUB_OUTPUT
          echo "path=false" >> $GITHUB_OUTPUT
          
          # Check if each chart directory has changes
          echo "$CHANGED_FILES" | grep -q "charts/guard/" && echo "guard=true" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" | grep -q "charts/watch/" && echo "watch=true" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" | grep -q "charts/path/" && echo "path=true" >> $GITHUB_OUTPUT
          
          # Output results for logging
          echo "Guard chart changed: $(echo "$CHANGED_FILES" | grep -q "charts/guard/" && echo "true" || echo "false")"
          echo "Watch chart changed: $(echo "$CHANGED_FILES" | grep -q "charts/watch/" && echo "true" || echo "false")"
          echo "Path chart changed: $(echo "$CHANGED_FILES" | grep -q "charts/path/" && echo "true" || echo "false")"
      
      # Debug chart changes
      - name: Debug chart changes
        run: |
          echo "Guard changed: ${{ steps.manual-filter.outputs.guard }}"
          echo "Watch changed: ${{ steps.manual-filter.outputs.watch }}"
          echo "Path changed: ${{ steps.manual-filter.outputs.path }}"
      
      # Build guard chart
      - name: Build guard chart
        if: steps.manual-filter.outputs.guard == 'true'
        run: |
          echo "Building guard chart..."
          mkdir -p .cr-local-charts
          helm dependency build charts/guard
          helm package charts/guard -d .cr-local-charts
      
      # Build watch chart
      - name: Build watch chart
        if: steps.manual-filter.outputs.watch == 'true'
        run: |
          echo "Building watch chart..."
          mkdir -p .cr-local-charts
          
          # Check dependency structure first
          yq_cmd="grep"
          if command -v yq &> /dev/null; then
            yq_cmd="yq"
          fi
          
          # If chart depends on guard, create local reference instead of repository
          if $yq_cmd "name: guard" charts/watch/Chart.yaml; then
            echo "Setting up local guard dependency for watch chart"
            
            # Create temporary Chart.yaml with local dependencies
            cat charts/watch/Chart.yaml > charts/watch/Chart.yaml.bak
            
            # Create local version of Chart.yaml - this is a simple approach, use a proper YAML parser in production
            sed -i 's|repository: .*github.io.*guard.*|repository: "file://$(pwd)/.cr-local-charts"|g' charts/watch/Chart.yaml || true
            sed -i 's|repository: "https://.*github.io.*guard.*|repository: "file://$(pwd)/.cr-local-charts"|g' charts/watch/Chart.yaml || true
            
            # Copy guard chart to local directory to ensure it's available
            if [ -f "$(ls -1 .cr-local-charts/guard-*.tgz 2>/dev/null | head -1)" ]; then
              echo "Using newly built guard chart"
            else
              echo "Building guard chart for dependency"
              helm dependency build charts/guard
              helm package charts/guard -d .cr-local-charts
            fi
          fi
          
          # Build with local dependencies
          echo "Chart.yaml contents for reference:"
          cat charts/watch/Chart.yaml
          
          helm dependency build charts/watch || (mv charts/watch/Chart.yaml.bak charts/watch/Chart.yaml && helm dependency build charts/watch)
          helm package charts/watch -d .cr-local-charts
          
          # Restore original Chart.yaml if we modified it
          if [ -f charts/watch/Chart.yaml.bak ]; then
            mv charts/watch/Chart.yaml.bak charts/watch/Chart.yaml
          fi
      
      # Build path chart
      - name: Build path chart
        if: steps.manual-filter.outputs.path == 'true'
        run: |
          echo "Building path chart..."
          mkdir -p .cr-local-charts
          
          # Check dependency structure first
          yq_cmd="grep"
          if command -v yq &> /dev/null; then
            yq_cmd="yq"
          fi
          
          # Create temporary Chart.yaml
          cat charts/path/Chart.yaml > charts/path/Chart.yaml.bak
          
          # Set up local guard dependency if it exists
          if $yq_cmd "name: guard" charts/path/Chart.yaml; then
            echo "Setting up local guard dependency for path chart"
            
            # Create local version of Chart.yaml
            sed -i 's|repository: .*github.io.*guard.*|repository: "file://$(pwd)/.cr-local-charts"|g' charts/path/Chart.yaml || true
            sed -i 's|repository: "https://.*github.io.*guard.*|repository: "file://$(pwd)/.cr-local-charts"|g' charts/path/Chart.yaml || true
            
            # Ensure guard chart is available
            if [ -f "$(ls -1 .cr-local-charts/guard-*.tgz 2>/dev/null | head -1)" ]; then
              echo "Using existing guard chart"
            else
              echo "Building guard chart for dependency"
              helm dependency build charts/guard
              helm package charts/guard -d .cr-local-charts
            fi
          fi
          
          # Set up local watch dependency if it exists
          if $yq_cmd "name: watch" charts/path/Chart.yaml; then
            echo "Setting up local watch dependency for path chart"
            
            # Create local version of Chart.yaml
            sed -i 's|repository: .*github.io.*watch.*|repository: "file://$(pwd)/.cr-local-charts"|g' charts/path/Chart.yaml || true
            sed -i 's|repository: "https://.*github.io.*watch.*|repository: "file://$(pwd)/.cr-local-charts"|g' charts/path/Chart.yaml || true
            
            # Ensure watch chart is available
            if [ -f "$(ls -1 .cr-local-charts/watch-*.tgz 2>/dev/null | head -1)" ]; then
              echo "Using existing watch chart"
            else
              echo "Building watch chart for dependency"
              helm dependency build charts/watch
              helm package charts/watch -d .cr-local-charts
            fi
          fi
          
          # Build with local dependencies
          echo "Chart.yaml contents for reference:"
          cat charts/path/Chart.yaml
          
          helm dependency build charts/path || (mv charts/path/Chart.yaml.bak charts/path/Chart.yaml && helm dependency build charts/path)
          helm package charts/path -d .cr-local-charts
          
          # Restore original Chart.yaml
          if [ -f charts/path/Chart.yaml.bak ]; then
            mv charts/path/Chart.yaml.bak charts/path/Chart.yaml
          fi
      
      # Phase 2: Move all packaged charts to release directory
      - name: Prepare charts for release
        if: steps.manual-filter.outputs.guard == 'true' || steps.manual-filter.outputs.watch == 'true' || steps.manual-filter.outputs.path == 'true'
        run: |
          mkdir -p .cr-release-packages
          if [ -d ".cr-local-charts" ]; then
            cp .cr-local-charts/*.tgz .cr-release-packages/ || true
            echo "Charts ready for release:"
            ls -la .cr-release-packages/
          fi
      
      # Upload all packaged charts at once
      - name: Upload charts
        if: steps.manual-filter.outputs.guard == 'true' || steps.manual-filter.outputs.watch == 'true' || steps.manual-filter.outputs.path == 'true'
        run: |
          if [ -n "$(ls -A .cr-release-packages)" ]; then
            echo "Uploading packaged charts..."
            cr upload -o "${{ github.repository_owner }}" -r "${{ github.event.repository.name }}" -p .cr-release-packages --token "${{ secrets.GITHUB_TOKEN }}" --skip-existing
          else
            echo "No charts to upload"
          fi
      
      # Update the Helm chart index
      - name: Update and push chart index
        if: steps.manual-filter.outputs.guard == 'true' || steps.manual-filter.outputs.watch == 'true' || steps.manual-filter.outputs.path == 'true'
        run: |
          if [ -n "$(ls -A .cr-release-packages)" ]; then
            echo "Updating Helm chart index..."
            cr index -o "${{ github.repository_owner }}" -r "${{ github.event.repository.name }}" -p .cr-release-packages --push
          else
            echo "No charts to index"
          fi
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
